[user]
name = "Jack Platten"
email = "jack@platten.me"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
show-cryptographic-signatures=true

[signing]
behavior = "drop"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHGminsJAXUJkc7TH7qHU6RNdZuMcWIwdx+zZCDpDiUG Personal"
backends.ssh.allowed-signers = "~/.ssh/allowed_signers"


[git]
sign-on-push = true
