[tools]
node = "20"
go = "1.24"
deno = "latest"
usage = "latest"
1password = "2.31.1"
youtube-dl = "latest"
python = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[env]
