[tools]
node = "20"
go = "latest"
deno = "latest"
usage = "latest"
1password = "latest"
youtube-dl = "latest"
python = "latest"
pnpm = "10"
rust = "1.92.0"
golangci-lint = "2.7.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[env]
